### ISSUE TITLE
x86 build error :error LNK2001: unresolved external symbol _GetDefaultKinectSensor@4

### ISSUE THREAD

**Issue by coderrrrrr** [hyrepo/kinect-projection-operation#1]
Hi Beginner,
        When I tried to build your project on x86 , it makes :error LNK2001: unresolved external symbol _GetDefaultKinectSensor@4 
        pls help me .Thx.

**Comment by hyrepo** [comment]
Seems like something wrong with ecvironment setting, I sent you an email with solutions, please check.

**Comment by coderrrrrr** [comment]
Thx, succeed. gonna close.
